Repository ourjapanlife/findadoc-server, pull requests merged in 2023-09, with the labels that each got.

#250 feat: make error code consistent
  src/errors.ts
Labels: backend

#254 docs: add anissa to contributors
  .all-contributorsrc
  README.md
Labels: documentation

#248 docs: update instructions for emulator
  README.md
  package.json
Labels: documentation, backend

#264 Refactor the error message tests
  __tests__/server.test.ts
  src/services/healthcareProfessionalService.ts
Labels: backend

#256 Add error messages/handeling to resolvers
  src/index.ts
  src/resolvers.ts
Labels: backend

#269 reworked facilities service
  src/errors.ts
  src/fakeData/facilities.ts
  src/fakeData/healthcareProfessionals.ts
  src/firebaseDb.ts
  src/resolvers.ts
  src/result.ts
  src/services/facilityService.ts
  src/services/healthcareProfessionalService.ts
  src/services/submissionService.ts
  src/typeDefs/dbSchema.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
  utils/stringUtils.ts
Labels: enhancement, schema, graphQL, security, code quality, backend

#265 Require all fields for addSubmission function
  src/resolvers.ts
  src/services/submissionService.ts
Labels: enhancement

#283 Add project name to dev:startlocaldb script
  package.json
Labels: bug, backend

#282 addSubmission method now saves an ID to the database
  src/services/submissionService.ts
Labels: enhancement

#288 test: add E2E test for newSubmission
  __tests__/submissionService.test.ts
  src/services/submissionService.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
  tsconfig.json
Labels: CI/CD, code quality, tests
