Repository ourjapanlife/findadoc-server, pull requests merged in 2023-12, with the labels that each got.

#358 Build out validation for degrees field of HP
  __tests__/healthcareProfessional.test.ts
  src/fakeData/fakeHealthcareProfessionals.ts
  src/services/healthcareProfessionalService.ts
  src/validation/validationHealthcareProfessional.ts
Labels: enhancement

#380 fixing pm2 cloud issue
  package.json
Labels: CI/CD, backend, deployment

#382 updating healthcheck url
  src/server.ts
Labels: enhancement, CI/CD, deployment

#391 added facility filtering by professional ids
  src/services/facilityService.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
Labels: enhancement, backend

#390 created search professionals resolver, service
  src/resolvers.ts
  src/services/healthcareProfessionalService.ts
  src/validation/validationHealthcareProfessional.ts
Labels: enhancement, backend

#392 adding new fields to professional and facility
  __tests__/facilities.test.ts
  __tests__/healthcareProfessional.test.ts
  package.json
  src/fakeData/fakeFacilities.ts
  src/fakeData/fakeHealthcareProfessionals.ts
  src/firebaseDb.ts
  src/server.ts
  src/services/facilityService.ts
  src/services/healthcareProfessionalService.ts
  src/typeDefs/dbSchema.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
  src/validation/validationHealthcareProfessional.ts
  utils/databaseSeedTool.ts
Labels: bug, enhancement, backend

#393 migrated to npm...for now
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .husky/pre-push
  README.md
  package-lock.json
  package.json
  src/firebaseDb.ts
  yarn.lock
Labels: CI/CD, backend, deployment

#394 removing the packagemanager entry
  package.json
Labels: bug

#395 fixing build script bug
  package.json
Labels: CI/CD, backend, deployment

#396 host is now an env variable
  .env.dev
  .env.prod
  src/server.ts
  utils/environmentVariables.ts
Labels: bug, CI/CD, backend, deployment

#397 removed auth from createsubmission
  src/resolvers.ts
Labels: backend

#398 allowing localhost calls to api
  src/server.ts
Labels: bug

#399 allowing localhost calls to api2
  src/server.ts
Labels: bug

#402 enable netlify previews to use api
  src/server.ts
Labels: backend

#405 enhanced professionals search
  __tests__/submissions.test.ts
  src/services/healthcareProfessionalService.ts
  src/services/submissionService.ts
Labels: enhancement, backend, tests

#370 Validate Create Submission Inputs
  package-lock.json
  src/services/submissionService.ts
  src/validation/validateSubmissions.ts
Labels: enhancement, backend

#410 fix: point the prod env to correct urls
  .env.prod
Labels: bug

#413 updated api url
  .env.prod
  src/auth.ts
Labels: backend

#414 fixing urls
  __tests__/testSetup.test.ts
  src/server.ts
Labels: enhancement, backend

#417 Build out validations for healthcare professional
  __tests__/healthcareProfessional.test.ts
  __tests__/healthcareProfessionalValidations.test.ts
  src/fakeData/fakeHealthcareProfessionals.ts
  src/services/healthcareProfessionalService.ts
  src/validation/validationHealthcareProfessional.ts
Labels: enhancement, backend
