Repository ourjapanlife/findadoc-server, pull requests merged in 2023-11, with the labels that each got.

#325 Rework schema, inputs, and tests
  .eslintrc.js
  .nvmrc
  .yarn/releases/yarn-3.6.4.cjs
  .yarn/releases/yarn-4.0.1.cjs
  .yarnrc.yml
  README.md
  __tests__/facilities.test.ts
  __tests__/healthcareProfessional.test.ts
  __tests__/server.test.ts
  __tests__/submissions.test.ts
  __tests__/testSetup.test.ts
  eslint.config.js
  firebase.json
  jest.config.js
  package.json
  src/fakeData/facilities.ts
  src/fakeData/fakeFacilities.ts
  src/fakeData/fakeHealthcareProfessionals.ts
  src/fakeData/healthcareProfessionals.ts
  src/fakeData/submissions.ts
  src/firebaseDb.ts
  src/index.ts
  src/resolvers.ts
  src/result.ts
  src/schema.ts
  src/services/facilityService.ts
  src/services/healthcareProfessionalService.ts
  src/services/submissionService.ts
  src/typeDefs/dbSchema.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
  tsconfig.json
  utils/databaseSeedTool.ts
  utils/gqlTool.ts
  utils/stringUtils.ts
  utils/typeUtils.ts
  yarn.lock
Labels: enhancement, schema, graphQL, code quality, backend, tests

#350 Build out validation for healthcare professional names
  __tests__/healthcareProfessional.test.ts
  src/fakeData/fakeHealthcareProfessionals.ts
  src/result.ts
  src/services/healthcareProfessionalService.ts
  src/validation/validationHealthcareProfessional.ts
  utils/stringUtils.ts
Labels: enhancement

#352 Add validation for submission search filters and order by options
  src/result.ts
  src/services/submissionService.ts
  src/validation/validateSubmissions.ts
  utils/stringUtils.ts
Labels: enhancement, backend

#359 Created delete functions and resolvers
  __tests__/facilities.test.ts
  __tests__/healthcareProfessional.test.ts
  __tests__/submissions.test.ts
  package.json
  src/fakeData/fakeHealthcareProfessionals.ts
  src/fakeData/submissions.ts
  src/resolvers.ts
  src/services/facilityService.ts
  src/services/healthcareProfessionalService.ts
  src/services/submissionService.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
  utils/arrayUtils.ts
  yarn.lock
Labels: enhancement, backend
