Repository ourjapanlife/findadoc-server, pull requests merged in 2024-12, with the labels that each got.

#639 feat: Add audit trail for create, update and delete healthcare profes…
  src/resolvers.ts
  src/services/auditLogService.ts
  src/services/facilityService.ts
  src/services/healthcareProfessionalService.ts
  src/services/submissionService.ts
  utils/databaseSeedTool.ts
Labels: enhancement, backend

#498 feat: implement function to procure facility submission details
  package-lock.json
  package.json
  src/resolvers.ts
  src/result.ts
  src/services/submissionService.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
  utils/environmentVariables.ts
  utils/submissionDataFromGoogleMaps.ts
Labels: enhancement, backend

#646 refactor: change the parameter types for createAuditLog
  src/services/auditLogService.ts
  src/services/submissionService.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
Labels: backend

#647 fix: add conditionals to allow updating specific fields
  src/services/healthcareProfessionalService.ts
Labels: bug, backend

#660 fix: update data type of newAuditLog argument in createAuditLog test
  __tests__/auditTrail.test.ts
Labels: bug
