Repository ourjapanlife/findadoc-server, pull requests merged in 2025-08, with the labels that each got.

#865 fix: update permission function
  src/auth.ts
Labels: bug, backend

#866 chore: add mongolian to Locale enum
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
Labels: schema, backend

#868 fix: update isAuthorized to use conditional due to functionality
  src/resolvers.ts
Labels: bug

#884 feat: figure out how to run the two tasks together
  package.json
  yarn.lock
Labels: enhancement, CI/CD

#885 feat: improved seeding tool and seed data
  .gitignore
  src/fakeData/fakeFacilities.ts
  src/fakeData/fakeHealthcareProfessionals.ts
  utils/databaseSeedTool.ts
Labels: enhancement
