Repository ourjapanlife/findadoc-server, pull requests merged in 2025-06, with the labels that each got.

#791 fix: fixed auth permission issue for dev role access
  src/auth.ts
Labels: bug, security

#793 refactor: update logic to handle submissions to just be facility or hp
  src/services/submissionService.ts
Labels: backend

#811 fix: fix submission bug
  src/services/submissionService.ts
Labels: bug

#814 feat: add categories for specialties
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
Labels: schema, backend
