Repository ourjapanlife/findadoc-server, pull requests merged in 2025-05, with the labels that each got.

#739 fix: change urls in README to consistent slug for gitbook
  README.md
Labels: bug, documentation

#737 feat: Implemented auth
  .husky/pre-push
  __tests__/auth.test.ts
  __tests__/healthcareProfessionalValidations.test.ts
  __tests__/testSetup.test.ts
  package.json
  src/auth.ts
  src/index.ts
  src/resolvers.ts
  src/server.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
  utils/environmentVariables.ts
  yarn.lock
Labels: enhancement

#780 feat: implement updated CORS for frontend deploy previews
  src/server.ts
Labels: CI/CD, backend

#781 fix: fix typescript error with typecasting
  src/server.ts
Labels: bug, code quality, backend
