Repository ourjapanlife/findadoc-server, pull requests merged in 2025-07, with the labels that each got.

#817 refactor: add additionalInfoForPatients field to hp
  __tests__/healthcareProfessional.test.ts
  __tests__/healthcareProfessionalValidations.test.ts
  src/fakeData/fakeHealthcareProfessionals.ts
  src/services/healthcareProfessionalService.ts
  src/typeDefs/gqlTypes.ts
  src/typeDefs/schema.graphql
Labels: enhancement, schema, backend

#847 fix: update mapping to set additional info to empty string instead of undefined
  src/services/healthcareProfessionalService.ts
Labels: bug, backend

#856 fix: change permission scope for creating submission
  __tests__/auth.test.ts
  src/auth.ts
  src/resolvers.ts
Labels: bug
