Repository ourjapanlife/findadoc-server, pull requests merged in 2025-01, with the labels that each got.

#670 feat: add audit trailing to facility service actions create, update and delete
  src/resolvers.ts
  src/services/facilityService.ts
  src/services/healthcareProfessionalService.ts
  src/services/submissionService.ts
  utils/databaseSeedTool.ts
Labels: enhancement

#688 fix: change facilities relations update on healthcare professional
  src/services/facilityService.ts
  src/services/healthcareProfessionalService.ts
Labels: bug

#690 BUG: Adding fix for digitalocean build
  package.json
Labels: bug, CI/CD

#691 fix: remove yarn from packageManager field
  package.json
Labels: bug

#692 chore: downgrade yarn to 4.3.1
  .yarn/releases/yarn-4.3.1.cjs
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: deployment
